# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'
dpr_grail:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.entities
dpr_epr:
  _target_: dpr.data.retriever_data.EPRCtxSrc
  setup_type: ???
  task_name: ???
  
dpr_b2f_medium:
  _target_: dpr.data.retriever_data.EPRCtxSrc
  setup_type: qa
  task_name: b2f_medium

  # id_prefix: 'grail:'