# cwd: ???
batch_size: 1

# model_name: 'google/t5-v1_1-xl'
model_name: "/data/jiaweilu/EleutherAI/gpt-neo-2.7B/"
#model_name: "EleutherAI/gpt-j-6B"
#model_name: "/data/jiaweilu/codellama-13b/models--codellama--CodeLlama-13b-hf/snapshots/a49a368460ad22e43dfffb97a1e1b826a6418d3b/"
output_file: ???
# length_file: ???
prompt_file: ???
max_length: 16384
num_prompts: -1
data_num: -1
task_name: ???
gen: True
order: ascending
#template_idx: ???
# model_name: 'google/t5-v1_1-small'
dataset_reader:
  _target_: src.dataset_readers.few_shot_dsr.FewShotDatasetReader
  model_name: ${model_name}
  task_name: ${task_name} 
    # _target_: src.dataset_readers.tasks.break_task.BreakTask
  prompt_file: ${prompt_file}
  # length_file: ${length_file}
  num_prompts: ${num_prompts}
  gen: ${gen}
  data_num: ${data_num}
  order: ${order}
#  template_idx: ${template_idx}
  
model:
  _target_: src.models.model.get_model
  # _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: ${model_name}
  

